version: "3.8"
services:
  auth:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
    env_file:
      - .env
#    environment:
#      - DB_HOST=db
    ports:
      - "3000:3000"
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    ports:
      - '5432:5432'
    volumes:
      - "/postgres-data:/var/lib/postgresql/data"